#!/bin/bash

# Move into tools directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

# Move into home directory
cd ..

bazel build //android:app
adb install bazel-bin/android/app.apk